AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  OpenIdClientServless:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: open-id-client-serverless/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64

